version: "3.8"
services:
  database:
    image: postgres
    restart: always
    # env_file: .env
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=products
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
  server:
    build:
      context: .
      dockerfile: Dockerfile
    # env_file: .env
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=products
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
    depends_on:
      - database
    networks:
      - default
    ports:
      - "3010:3010"
volumes:
  data: