# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.14
      # - image: circleci/postgres:latest
      #   environment: # environment variables for primary container
      #     POSTGRES_USER: root
      #     POSTGRES_DB: secret

      # - image: migrate/migrate

    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      # - run:
      #     name: "Git clone"
      #     command: "git clone $CIRCLE_REPOSITORY_URL /tmp/_circleci_local_build_repo"
      - checkout
      - run: 
          name: Getting dependencies
          command: go get -v -t -d ./...
      # - run:
      #     name: Waiting for Postgres to be ready
      #     command: dockerize -wait tcp://localhost:5432 -timeout 2m
      # - run:
      #     name: Running integration tests
      #     command: go test -v ./...
      - run:
          name: Building...
          command: go build -v -o go-app-circleci
      

      
      # - run: go test -v ./... 